[package]
name = "surjective-enum"
version = "0.1.0"
authors = ["Robert Hennig <robert@freylax.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
